### ISSUE TITLE
Please keep binary compatibility for same major version

### ISSUE THREAD

**Issue by anatawa12** [ajalt/clikt#221]
When I use Clikt 2.8.0 and kotest-runner-console-jvm 4.1.3, we cannot execute kotest with the error shown below: 

```
Exception in thread "main" java.lang.NoSuchMethodError: com.github.ajalt.clikt.core.CliktCommand.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZLjava/util/Map;Ljava/lang/String;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at io.kotest.runner.console.Execute.<init>(launcher.kt:16)
	at io.kotest.runner.console.LauncherKt.main(launcher.kt:14)
```

This error is thrown because Clikt breaks binary compatibility between 2.8.0 and 2.6.0. kotest-runner-console-jvm uses Clikt 2.6.0. [see Libs.kt#L21 at v4.1.2](https://github.com/kotest/kotest/blob/v4.1.2/buildSrc/src/main/kotlin/Libs.kt#L21)

Please keep binary compatibility for same major version.

**Comment by ajalt** [comment]
Absolutely. That's the plan going forward.
