### ISSUE TITLE
Allow duplicate options under different subcommands

### ISSUE THREAD

**Issue by trietsch** [ajalt/clikt#262]
Currently, it's not possible to use the same option name, even though you register the option under a different subcommand.

Running an app that tries this, results in the following:

```
Exception in thread "main" java.lang.IllegalArgumentException: Duplicate option name -t
	at com.github.ajalt.clikt.core.CliktCommand.registerOption(CliktCommand.kt:194)
	at com.github.ajalt.clikt.core.CliktCommand.registerOption(CliktCommand.kt:199)
	at com.github.ajalt.clikt.parameters.options.OptionWithValues.provideDelegate(OptionWithValues.kt:157)
	at com.example.api.cli.commands.OutputsCreate.<init>(Outputs.kt:86)
	at com.example.api.cli.commands.Outputs.<init>(Outputs.kt:32)
	at com.example.api.cli.MyCli.<init>(Application.kt:31)
	at com.example.api.cli.ApplicationKt.main(Application.kt:15)
```

Affected version:

```
<dependency>
    <groupId>com.github.ajalt.clikt</groupId>
    <artifactId>clikt-jvm</artifactId>
    <version>3.1.0</version>
</dependency>
```

**Comment by trietsch** [comment]
Alright, seems that I misconfigured my app and that I missed a duplicate. Sorry for creating an issue!
