### ISSUE TITLE
Default value for option when no value is passed

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#381]
Is there currently a way to achieve the following behavior (for an exemplary `--foo` string option):
- If `--foo` is not specified on the CLI, set the variable to `null`.
- If `--foo` is specified without a value, apply a default value.
- If `--foo` is specified with a value, use that value.

**Comment by JakeWharton** [comment]
Not in 3.x, but in 4.0 (currently available as a snapshot) you will be able to: https://github.com/ajalt/clikt/blob/4.0/docs/options.md#options-with-an-optional-value

Per https://kotlinlang.slack.com/archives/C010B2LR509/p1666710542317029

**Comment by sschuberth** [comment]
Thanks for the answer and reference!

**Comment by sschuberth** [comment]
Unfortunately, `optionalValue` currently does not work when using the value of another option:

```
Exception in thread "main" java.lang.IllegalStateException: Cannot read from argument delegate before parsing command line
        at com.github.ajalt.clikt.parameters.internal.NullableLateinit.getValue(NullableLateinit.kt:18)
        at com.github.ajalt.clikt.parameters.arguments.ProcessedArgumentImpl.getValue(Argument.kt:174)
        at com.github.ajalt.clikt.parameters.arguments.ProcessedArgumentImpl.getValue(Argument.kt:188)
        at com.github.ajalt.clikt.parameters.arguments.ProcessedArgumentImpl.getValue(Argument.kt:155)
        at org.ossreviewtoolkit.helper.commands.classifications.ImportCommand.getProvider(ImportCommand.kt:48)
        at org.ossreviewtoolkit.helper.commands.classifications.ImportCommand.<init>(ImportCommand.kt:56)
        at org.ossreviewtoolkit.helper.commands.classifications.LicenseClassificationsCommand.<init>(LicenseClassificationsCommand.kt:32)
        at org.ossreviewtoolkit.helper.HelperMain.<init>(HelperMain.kt:89)
        at org.ossreviewtoolkit.helper.HelperMainKt.main(HelperMain.kt:54)
```

Would it make sense to get something like `optionalValueLazy`, similar to `defaultLazy`?
