### ISSUE TITLE
Version 4.0.0 stopped working with GraalVM native-image

### ISSUE THREAD

**Issue by morki** [ajalt/clikt#415]
```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Proxy class defined by interfaces [interface com.github.ajalt.mordant.internal.PosixLibC] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:92)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:171)
	at java.base@17.0.7/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:47)
	at java.base@17.0.7/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1037)
	at com.sun.jna.Native.load(Native.java:624)
	at com.sun.jna.Native.load(Native.java:596)
	at com.github.ajalt.mordant.internal.LinuxMppImpls.<init>(JnaMppImplsLinux.kt:44)
	at com.github.ajalt.mordant.internal.MppImplKt.<clinit>(MppImpl.kt:97)
	at com.github.ajalt.mordant.terminal.TerminalDetection.isJediTerm(TerminalDetection.kt:143)
	at com.github.ajalt.mordant.terminal.TerminalDetection.isIntellijRunActionConsole(TerminalDetection.kt:169)
	at com.github.ajalt.mordant.terminal.TerminalDetection.detectTerminal(TerminalDetection.kt:16)
	at com.github.ajalt.mordant.terminal.StdoutTerminalInterface.<init>(StdoutTerminalInterface.kt:17)
	at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:56)
	at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:45)
	at com.github.ajalt.clikt.core.Context$Builder.<init>(Context.kt:227)
	at com.github.ajalt.clikt.core.Context$Companion.build$clikt(Context.kt:312)
	at com.github.ajalt.clikt.core.CliktCommand.createContext(CliktCommand.kt:141)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:487)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:486)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:506)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:513)
```

**Comment by ajalt** [comment]
Hmm, I've never used Graal. This looks like it's due to [JNA][1], which Mordant uses for terminal detection. Can you update your Graal configuration to support JNA's proxies?

[1]: https://github.com/java-native-access/jna
