### ISSUE TITLE
Getting " Cannot read from option delegate before parsing command line" with clikt 4

### ISSUE THREAD

**Issue by sschuberth** [ajalt/clikt#430]
After the upgrade to clikt 4, we're getting a "Cannot read from option delegate before parsing command line" `IllegalStateException` where there was none before. Compare running `./gradlew :cli:run --args="analyze"` on https://github.com/oss-review-toolkit/ort.

Current `main`using clikt 4.1.0 gives

```
Exception in thread "main" java.lang.IllegalStateException: Cannot read from option delegate before parsing command line
        at com.github.ajalt.clikt.parameters.internal.NullableLateinit.getValue(NullableLateinit.kt:18)
        at com.github.ajalt.clikt.parameters.options.OptionWithValuesImpl.getValue(OptionWithValues.kt:184)
        at com.github.ajalt.clikt.parameters.options.OptionDelegate$DefaultImpls.getValue(Option.kt:108)
        at com.github.ajalt.clikt.parameters.options.OptionWithValues$DefaultImpls.getValue(OptionWithValues.kt:88)
        at com.github.ajalt.clikt.parameters.options.OptionWithValuesImpl.getValue(OptionWithValues.kt:159)
        at com.github.ajalt.clikt.parameters.options.OptionWithValuesImpl.getValue(OptionWithValues.kt:159)
        at org.ossreviewtoolkit.plugins.commands.analyzer.AnalyzerCommand.getInputDir(AnalyzerCommand.kt:68)
        at org.ossreviewtoolkit.plugins.commands.analyzer.AnalyzerCommand.access$getInputDir(AnalyzerCommand.kt:62)
        at org.ossreviewtoolkit.plugins.commands.analyzer.AnalyzerCommand$special$$inlined$defaultLazy$default$1.invoke(TransformAll.kt:240)
        at org.ossreviewtoolkit.plugins.commands.analyzer.AnalyzerCommand$special$$inlined$defaultLazy$default$1.invoke(TransformAll.kt:95)
        at com.github.ajalt.clikt.parameters.options.OptionWithValuesImpl.finalize(OptionWithValues.kt:221)
        at com.github.ajalt.clikt.internal.FinalizationKt.finalizeOptions(Finalization.kt:45)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:252)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:489)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:486)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:506)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:513)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:66)
```

whereas running on commit [62279c93b5bd7dacab85abc8080ba0a459e1adf2](https://github.com/oss-review-toolkit/ort/commit/62279c93b5bd7dacab85abc8080ba0a459e1adf2) with clikt 3.5.4 gives

```
Usage: ort analyze [OPTIONS]

Error: Missing option "--input-dir"
```

The relevant command is [here](https://github.com/oss-review-toolkit/ort/blob/main/plugins/commands/analyzer/src/main/kotlin/AnalyzerCommand.kt).

Is this a regression, or and intended change in behavior we need to adapt to?

**Comment by ajalt** [comment]
Thanks for the report, this was a regression.
