### ISSUE TITLE
error when running in a docker container

### ISSUE THREAD

**Issue by eean** [ajalt/clikt#436]
It's quite possible this error is an issue with the environment being a bit broken, it's a docker container I have hacked up to run systemd to be full system like. Ideally it would just fall back to simpler functionality if there's an error loading the c library.

This was with Clikt 4.2.0

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/jna11924925260265220916.tmp: /tmp/jna11924925260265220916.tmp: failed to map segment from shared object
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
        at com.sun.jna.Native.<clinit>(Native.java:221)
        at com.github.ajalt.mordant.internal.LinuxMppImpls.<init>(JnaMppImplsLinux.kt:44)
        at com.github.ajalt.mordant.internal.MppImplKt.<clinit>(MppImpl.kt:97)
        at com.github.ajalt.mordant.terminal.TerminalDetection.isJediTerm(TerminalDetection.kt:143)
        at com.github.ajalt.mordant.terminal.TerminalDetection.isIntellijRunActionConsole(TerminalDetection.kt:169)
        at com.github.ajalt.mordant.terminal.TerminalDetection.detectTerminal(TerminalDetection.kt:16)
        at com.github.ajalt.mordant.terminal.StdoutTerminalInterface.<init>(StdoutTerminalInterface.kt:17)
        at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:56)
        at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:45)
        at com.github.ajalt.clikt.core.Context$Builder.<init>(Context.kt:227)
        at com.github.ajalt.clikt.core.Context$Companion.build$clikt(Context.kt:312)
        at com.github.ajalt.clikt.core.CliktCommand.createContext(CliktCommand.kt:141)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:456)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
```

**Comment by ajalt** [comment]
This should be fixed in 4.2.1.
